//! Integration tests for `braze-sync export` (Catalog Schema).
//!
//! Each test stands up a wiremock server, writes a temporary
//! braze-sync.config.yaml that points the api_endpoint at the mock,
//! invokes the real binary via assert_cmd, and asserts on the resulting
//! filesystem state and exit code.
//!
//! Tests use `flavor = "multi_thread"` so wiremock can serve HTTP
//! requests on a worker thread while the test thread is parked in
//! `spawn_blocking` waiting on the subprocess. Single-threaded
//! `#[tokio::test]` would deadlock because the blocking subprocess wait
//! would hold the only worker.

mod common;

use assert_cmd::Command;
use common::write_config;
use serde_json::json;
use std::fs;
use wiremock::matchers::{method, path};
use wiremock::{Mock, MockServer, ResponseTemplate};

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn export_catalog_schemas_writes_files_and_exits_zero() {
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path("/catalogs"))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "catalogs": [
                {
                    "name": "cardiology",
                    "description": "Cardiology catalog",
                    "fields": [
                        {"name": "id", "type": "string"},
                        {"name": "score", "type": "number"}
                    ]
                },
                {
                    "name": "dermatology",
                    "fields": [
                        {"name": "id", "type": "string"}
                    ]
                }
            ]
        })))
        .mount(&server)
        .await;

    let tmp = tempfile::tempdir().unwrap();
    let config_path = write_config(tmp.path(), &server.uri());
    let tmp_path = tmp.path().to_path_buf();

    tokio::task::spawn_blocking(move || {
        Command::cargo_bin("braze-sync")
            .unwrap()
            .env("BRAZE_API_KEY", "test-key")
            .args(["--config", config_path.to_str().unwrap()])
            .args(["export", "--resource", "catalog_schema"])
            .assert()
            .success();
    })
    .await
    .unwrap();

    let cardiology = tmp_path.join("catalogs/cardiology/schema.yaml");
    let dermatology = tmp_path.join("catalogs/dermatology/schema.yaml");
    assert!(cardiology.exists(), "cardiology schema should exist");
    assert!(dermatology.exists(), "dermatology schema should exist");

    let content = fs::read_to_string(&cardiology).unwrap();
    assert!(content.contains("name: cardiology"));
    assert!(content.contains("- name: id"));
    assert!(content.contains("- name: score"));
    assert!(content.starts_with("# Generated by braze-sync."));
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn export_with_name_filter_uses_get_endpoint() {
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path("/catalogs/cardiology"))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "catalogs": [
                {"name": "cardiology", "fields": [{"name": "id", "type": "string"}]}
            ]
        })))
        .mount(&server)
        .await;

    let tmp = tempfile::tempdir().unwrap();
    let config_path = write_config(tmp.path(), &server.uri());
    let tmp_path = tmp.path().to_path_buf();

    tokio::task::spawn_blocking(move || {
        Command::cargo_bin("braze-sync")
            .unwrap()
            .env("BRAZE_API_KEY", "test-key")
            .args(["--config", config_path.to_str().unwrap()])
            .args([
                "export",
                "--resource",
                "catalog_schema",
                "--name",
                "cardiology",
            ])
            .assert()
            .success();
    })
    .await
    .unwrap();

    assert!(
        tmp_path.join("catalogs/cardiology/schema.yaml").exists(),
        "cardiology schema should exist after --name export"
    );
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn unauthorized_braze_response_yields_exit_code_4() {
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path("/catalogs"))
        .respond_with(ResponseTemplate::new(401).set_body_string("invalid api key"))
        .mount(&server)
        .await;

    let tmp = tempfile::tempdir().unwrap();
    let config_path = write_config(tmp.path(), &server.uri());

    tokio::task::spawn_blocking(move || {
        Command::cargo_bin("braze-sync")
            .unwrap()
            .env("BRAZE_API_KEY", "wrong-key")
            .args(["--config", config_path.to_str().unwrap()])
            .args(["export", "--resource", "catalog_schema"])
            .assert()
            .failure()
            .code(4);
    })
    .await
    .unwrap();
}

#[test]
fn missing_config_file_yields_exit_code_3() {
    Command::cargo_bin("braze-sync")
        .unwrap()
        .env("BRAZE_API_KEY", "anything")
        .args(["--config", "/nonexistent/braze-sync.config.yaml"])
        .args(["export"])
        .assert()
        .failure()
        .code(3);
}

#[test]
fn invalid_args_name_without_resource_yields_exit_code_3() {
    // clap rejects --name without --resource at parse time. We expect
    // exit 3 (config / argument error).
    Command::cargo_bin("braze-sync")
        .unwrap()
        .args(["export", "--name", "x"])
        .assert()
        .failure()
        .code(3);
}

#[test]
fn help_flag_exits_zero() {
    Command::cargo_bin("braze-sync")
        .unwrap()
        .arg("--help")
        .assert()
        .success();
}

// =====================================================================
// Content Block (v0.2.0)
// =====================================================================

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn export_content_blocks_writes_liquid_files() {
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path("/content_blocks/list"))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "content_blocks": [
                {"content_block_id": "id-promo", "name": "promo"},
                {"content_block_id": "id-header", "name": "shared_header"}
            ],
            "message": "success"
        })))
        .mount(&server)
        .await;
    Mock::given(method("GET"))
        .and(path("/content_blocks/info"))
        .and(wiremock::matchers::query_param(
            "content_block_id",
            "id-promo",
        ))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "content_block_id": "id-promo",
            "name": "promo",
            "description": "Promo banner",
            "content": "Hello {{ user.${first_name} }}",
            "tags": ["pr"],
            "message": "success"
        })))
        .mount(&server)
        .await;
    Mock::given(method("GET"))
        .and(path("/content_blocks/info"))
        .and(wiremock::matchers::query_param(
            "content_block_id",
            "id-header",
        ))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "content_block_id": "id-header",
            "name": "shared_header",
            "content": "<header>shared</header>",
            "tags": [],
            "message": "success"
        })))
        .mount(&server)
        .await;

    let tmp = tempfile::tempdir().unwrap();
    let config_path = write_config(tmp.path(), &server.uri());
    let tmp_path = tmp.path().to_path_buf();

    tokio::task::spawn_blocking(move || {
        Command::cargo_bin("braze-sync")
            .unwrap()
            .env("BRAZE_API_KEY", "test-key")
            .args(["--config", config_path.to_str().unwrap()])
            .args(["export", "--resource", "content_block"])
            .assert()
            .success();
    })
    .await
    .unwrap();

    let promo = tmp_path.join("content_blocks/promo.liquid");
    let header = tmp_path.join("content_blocks/shared_header.liquid");
    assert!(promo.exists(), "promo.liquid should exist");
    assert!(header.exists(), "shared_header.liquid should exist");

    let promo_text = fs::read_to_string(&promo).unwrap();
    assert!(promo_text.starts_with("---\n"));
    assert!(promo_text.contains("name: promo"));
    assert!(promo_text.contains("description: Promo banner"));
    assert!(promo_text.contains("Hello {{ user.${first_name} }}"));
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn export_content_block_with_name_filter_only_fetches_matching_info() {
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path("/content_blocks/list"))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "content_blocks": [
                {"content_block_id": "id-promo", "name": "promo"},
                {"content_block_id": "id-header", "name": "shared_header"}
            ]
        })))
        .mount(&server)
        .await;
    // Only the matching info call should fire; the non-matching one
    // would hit this 500 mock and fail the test.
    Mock::given(method("GET"))
        .and(path("/content_blocks/info"))
        .and(wiremock::matchers::query_param(
            "content_block_id",
            "id-header",
        ))
        .respond_with(ResponseTemplate::new(500))
        .expect(0)
        .mount(&server)
        .await;
    Mock::given(method("GET"))
        .and(path("/content_blocks/info"))
        .and(wiremock::matchers::query_param(
            "content_block_id",
            "id-promo",
        ))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "name": "promo",
            "content": "x",
            "tags": []
        })))
        .mount(&server)
        .await;

    let tmp = tempfile::tempdir().unwrap();
    let config_path = write_config(tmp.path(), &server.uri());
    let tmp_path = tmp.path().to_path_buf();

    tokio::task::spawn_blocking(move || {
        Command::cargo_bin("braze-sync")
            .unwrap()
            .env("BRAZE_API_KEY", "test-key")
            .args(["--config", config_path.to_str().unwrap()])
            .args(["export", "--resource", "content_block", "--name", "promo"])
            .assert()
            .success();
    })
    .await
    .unwrap();

    assert!(tmp_path.join("content_blocks/promo.liquid").exists());
    assert!(!tmp_path
        .join("content_blocks/shared_header.liquid")
        .exists());
}

// =====================================================================
// Email Template (v0.3.0)
// =====================================================================

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn export_email_templates_writes_directory_layout() {
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path("/templates/email/list"))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "templates": [
                {"email_template_id": "id-welcome", "template_name": "welcome"}
            ]
        })))
        .mount(&server)
        .await;
    Mock::given(method("GET"))
        .and(path("/templates/email/info"))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "template_name": "welcome",
            "subject": "Welcome to our service",
            "body": "<p>Hello</p>",
            "plaintext_body": "Hello",
            "description": "Welcome email",
            "preheader": "Get started",
            "tags": ["onboarding"],
            "message": "success"
        })))
        .mount(&server)
        .await;

    let tmp = tempfile::tempdir().unwrap();
    let config_path = write_config(tmp.path(), &server.uri());
    let tmp_path = tmp.path().to_path_buf();

    tokio::task::spawn_blocking(move || {
        Command::cargo_bin("braze-sync")
            .unwrap()
            .env("BRAZE_API_KEY", "test-key")
            .args(["--config", config_path.to_str().unwrap()])
            .args(["export", "--resource", "email_template"])
            .assert()
            .success();
    })
    .await
    .unwrap();

    let et_dir = tmp_path.join("email_templates/welcome");
    assert!(et_dir.join("template.yaml").exists());
    assert!(et_dir.join("body.html").exists());
    assert!(et_dir.join("body.txt").exists());

    let yaml = fs::read_to_string(et_dir.join("template.yaml")).unwrap();
    assert!(yaml.contains("name: welcome"));
    assert!(yaml.contains("subject: Welcome to our service"));
    let html = fs::read_to_string(et_dir.join("body.html")).unwrap();
    assert_eq!(html, "<p>Hello</p>");
    let txt = fs::read_to_string(et_dir.join("body.txt")).unwrap();
    assert_eq!(txt, "Hello");
}

// =====================================================================
// Custom Attribute
// =====================================================================

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn export_custom_attributes_writes_registry_yaml() {
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path("/custom_attributes"))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "attributes": [
                {
                    "name": "last_visit_date",
                    "data_type": "date",
                    "description": "Most recent visit",
                    "status": "Active"
                },
                {
                    "name": "preferred_clinic_id",
                    "data_type": "string",
                    "description": "User's preferred clinic",
                    "status": "Active"
                },
                {
                    "name": "legacy_segment",
                    "data_type": "string",
                    "status": "Blocklisted"
                }
            ],
            "message": "success"
        })))
        .mount(&server)
        .await;

    let tmp = tempfile::tempdir().unwrap();
    let config_path = write_config(tmp.path(), &server.uri());
    let tmp_path = tmp.path().to_path_buf();

    tokio::task::spawn_blocking(move || {
        Command::cargo_bin("braze-sync")
            .unwrap()
            .env("BRAZE_API_KEY", "test-key")
            .args(["--config", config_path.to_str().unwrap()])
            .args(["export", "--resource", "custom_attribute"])
            .assert()
            .success();
    })
    .await
    .unwrap();

    let registry_path = tmp_path.join("custom_attributes/registry.yaml");
    assert!(registry_path.exists(), "registry.yaml should exist");
    let content = fs::read_to_string(&registry_path).unwrap();
    assert!(content.contains("last_visit_date"));
    assert!(content.contains("preferred_clinic_id"));
    assert!(content.contains("legacy_segment"));
    assert!(content.contains("deprecated: true"));
    // Verify sorted order (last_visit_date < legacy_segment < preferred_clinic_id)
    let pos_last = content.find("last_visit_date").unwrap();
    let pos_legacy = content.find("legacy_segment").unwrap();
    let pos_pref = content.find("preferred_clinic_id").unwrap();
    assert!(pos_last < pos_legacy);
    assert!(pos_legacy < pos_pref);
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn export_content_block_preserves_local_template_and_refreshes_values() {
    // v0.15: when a local template uses `__BRAZESYNC.*__`, export must
    // preserve the local body verbatim. The values file is NOT touched
    // — lid / cb_id are resolved at apply/diff time from the remote.
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path("/content_blocks/list"))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "content_blocks": [{"content_block_id": "id-promo", "name": "promo"}]
        })))
        .mount(&server)
        .await;
    Mock::given(method("GET"))
        .and(path("/content_blocks/info"))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "name": "promo",
            "content": "<a href=\"https://example.com/cta\">{{ x | lid: 'newlidvalue1' }}go</a>",
            "tags": []
        })))
        .mount(&server)
        .await;

    let tmp = tempfile::tempdir().unwrap();
    let config_path = write_config(tmp.path(), &server.uri());
    common::write_local_content_block(
        tmp.path(),
        "promo",
        "<a href=\"https://example.com/cta\">{{ x | lid: '__BRAZESYNC__' }}go</a>",
    );

    tokio::task::spawn_blocking(move || {
        Command::cargo_bin("braze-sync")
            .unwrap()
            .env("BRAZE_API_KEY", "test-key")
            .args(["--config", config_path.to_str().unwrap()])
            .args(["export", "--resource", "content_block"])
            .assert()
            .success();
    })
    .await
    .unwrap();

    let saved = fs::read_to_string(tmp.path().join("content_blocks").join("promo.liquid")).unwrap();
    assert!(
        saved.contains("__BRAZESYNC__"),
        "local template body must survive export round-trip, got:\n{saved}"
    );
    assert!(
        !saved.contains("newlidvalue1"),
        "remote lid value must not bleed into the templated body, got:\n{saved}"
    );
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn export_captures_dashboard_html_edit_on_templated_content_block() {
    // Issue #54: when a local template uses `__BRAZESYNC__` and the
    // Dashboard user edits the surrounding HTML (not lid/cb_id), export
    // must reverse-templatize the remote body so the edit is captured
    // while placeholders stay anonymous.
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path("/content_blocks/list"))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "content_blocks": [{"content_block_id": "id-promo", "name": "promo"}]
        })))
        .mount(&server)
        .await;
    // Remote: dashboard user changed "go" → "Buy now"; lid value also
    // rotated (which alone should not produce drift).
    Mock::given(method("GET"))
        .and(path("/content_blocks/info"))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "name": "promo",
            "content": "<a href=\"https://example.com/cta\">{{ x | lid: 'rotatedlid1' }}Buy now</a>",
            "tags": []
        })))
        .mount(&server)
        .await;

    let tmp = tempfile::tempdir().unwrap();
    let config_path = write_config(tmp.path(), &server.uri());
    common::write_local_content_block(
        tmp.path(),
        "promo",
        "<a href=\"https://example.com/cta\">{{ x | lid: '__BRAZESYNC__' }}go</a>",
    );

    tokio::task::spawn_blocking(move || {
        Command::cargo_bin("braze-sync")
            .unwrap()
            .env("BRAZE_API_KEY", "test-key")
            .args(["--config", config_path.to_str().unwrap()])
            .args(["export", "--resource", "content_block"])
            .assert()
            .success();
    })
    .await
    .unwrap();

    let saved = fs::read_to_string(tmp.path().join("content_blocks").join("promo.liquid")).unwrap();
    assert!(
        saved.contains("Buy now"),
        "dashboard HTML edit must be captured, got:\n{saved}"
    );
    assert!(
        saved.contains("__BRAZESYNC__"),
        "lid placeholder must remain anonymous, got:\n{saved}"
    );
    assert!(
        !saved.contains("rotatedlid1"),
        "remote lid value must not bleed into the templated body, got:\n{saved}"
    );
    assert!(
        !saved.contains(">go<"),
        "stale local copy must be replaced, got:\n{saved}"
    );
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn export_captures_dashboard_html_edit_on_templated_email_template() {
    // Issue #54: same property for email_template — Dashboard edits to
    // subject / body_html / body_plaintext / preheader on a templated
    // template must be captured field-by-field via reverse-templatize.
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path("/templates/email/list"))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "templates": [
                {"email_template_id": "id-welcome", "template_name": "welcome"}
            ]
        })))
        .mount(&server)
        .await;
    Mock::given(method("GET"))
        .and(path("/templates/email/info"))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "template_name": "welcome",
            "subject": "Welcome!",
            // Dashboard edited copy: "Hello" → "Hi there"; lid rotated.
            "body": "<a href=\"https://example.com/cta\">{{ x | lid: 'rotatedlid1' }}Hi there</a>",
            "plaintext_body": "Hi there",
            "preheader": "Get started today",
            "tags": [],
            "message": "success"
        })))
        .mount(&server)
        .await;

    let tmp = tempfile::tempdir().unwrap();
    let config_path = write_config(tmp.path(), &server.uri());
    common::write_local_email_template(
        tmp.path(),
        "welcome",
        "Welcome!",
        "<a href=\"https://example.com/cta\">{{ x | lid: '__BRAZESYNC__' }}Hello</a>",
        "Hello",
    );

    tokio::task::spawn_blocking(move || {
        Command::cargo_bin("braze-sync")
            .unwrap()
            .env("BRAZE_API_KEY", "test-key")
            .args(["--config", config_path.to_str().unwrap()])
            .args(["export", "--resource", "email_template"])
            .assert()
            .success();
    })
    .await
    .unwrap();

    let et_dir = tmp.path().join("email_templates/welcome");
    let html = fs::read_to_string(et_dir.join("body.html")).unwrap();
    assert!(html.contains("Hi there"), "dashboard edit captured: {html}");
    assert!(
        html.contains("__BRAZESYNC__"),
        "placeholder preserved: {html}"
    );
    assert!(
        !html.contains("rotatedlid1"),
        "remote lid must not leak: {html}"
    );
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn export_content_block_without_placeholders_is_unchanged() {
    // Backwards compat: a plain (no placeholder) content_block must
    // still be written verbatim from remote, and no values file
    // should be touched.
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path("/content_blocks/list"))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "content_blocks": [{"content_block_id": "id-plain", "name": "plain"}]
        })))
        .mount(&server)
        .await;
    Mock::given(method("GET"))
        .and(path("/content_blocks/info"))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "name": "plain",
            "content": "Hello world\n",
            "tags": []
        })))
        .mount(&server)
        .await;

    let tmp = tempfile::tempdir().unwrap();
    let config_path = write_config(tmp.path(), &server.uri());

    tokio::task::spawn_blocking(move || {
        Command::cargo_bin("braze-sync")
            .unwrap()
            .env("BRAZE_API_KEY", "test-key")
            .args(["--config", config_path.to_str().unwrap()])
            .args(["export", "--resource", "content_block"])
            .assert()
            .success();
    })
    .await
    .unwrap();

    let saved = fs::read_to_string(tmp.path().join("content_blocks").join("plain.liquid")).unwrap();
    assert!(saved.contains("Hello world"), "saved file: {saved}");
    assert!(
        !tmp.path().join("values").join("test.yaml").exists(),
        "no values file should be created for placeholder-free workspaces"
    );
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn export_leaves_legacy_values_yaml_unchanged() {
    // v0.15: export does not touch values yaml at all. A pre-existing
    // legacy `lid:` / `cb_id:` section is harmless — it is silently
    // dropped at load (use `braze-sync values cleanup` to physically
    // remove). Export must not regenerate or modify it.
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path("/content_blocks/list"))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "content_blocks": [{"content_block_id": "id-promo", "name": "promo"}]
        })))
        .mount(&server)
        .await;
    Mock::given(method("GET"))
        .and(path("/content_blocks/info"))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "name": "promo",
            "content": "<a href=\"https://example.com/cta\">{{ x | lid: 'newlidvalue1' }}go</a>",
            "tags": []
        })))
        .mount(&server)
        .await;

    let tmp = tempfile::tempdir().unwrap();
    let config_path = write_config(tmp.path(), &server.uri());
    common::write_local_content_block(
        tmp.path(),
        "promo",
        "<a href=\"https://example.com/cta\">{{ x | lid: '__BRAZESYNC__' }}go</a>",
    );
    let legacy = r#"version: 1
content_block:
  promo:
    lid:
      cta:
        value: oldlidvalue1
        url: https://example.com/cta
"#;
    common::write_values_file(tmp.path(), "test", legacy);

    tokio::task::spawn_blocking(move || {
        Command::cargo_bin("braze-sync")
            .unwrap()
            .env("BRAZE_API_KEY", "test-key")
            .args(["--config", config_path.to_str().unwrap()])
            .args(["export", "--resource", "content_block"])
            .assert()
            .success();
    })
    .await
    .unwrap();

    // export must leave the values file byte-identical.
    let after = fs::read_to_string(tmp.path().join("values").join("test.yaml")).unwrap();
    assert_eq!(after, legacy, "export must not touch the values yaml");
}

// =====================================================================
// Issue #59: new resources (no local file) must be templatized on export
// =====================================================================

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn export_new_content_block_templatizes_lid() {
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path("/content_blocks/list"))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "content_blocks": [{"content_block_id": "id-new", "name": "new_block"}]
        })))
        .mount(&server)
        .await;
    Mock::given(method("GET"))
        .and(path("/content_blocks/info"))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "name": "new_block",
            "content": "<a href=\"https://example.com\">{{ x | lid: 'abc123' }}click</a>",
            "tags": []
        })))
        .mount(&server)
        .await;

    let tmp = tempfile::tempdir().unwrap();
    let config_path = write_config(tmp.path(), &server.uri());
    // No local file — this is a brand-new resource.

    let tmp_path = tmp.path().to_path_buf();
    tokio::task::spawn_blocking(move || {
        Command::cargo_bin("braze-sync")
            .unwrap()
            .env("BRAZE_API_KEY", "test-key")
            .args(["--config", config_path.to_str().unwrap()])
            .args(["export", "--resource", "content_block"])
            .assert()
            .success();
    })
    .await
    .unwrap();

    let saved =
        fs::read_to_string(tmp_path.join("content_blocks").join("new_block.liquid")).unwrap();
    assert!(
        saved.contains("__BRAZESYNC__"),
        "new resource must be templatized, got:\n{saved}"
    );
    assert!(
        !saved.contains("abc123"),
        "raw lid value must not persist for new resources, got:\n{saved}"
    );
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn export_new_email_template_templatizes_lid() {
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path("/templates/email/list"))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "templates": [
                {"email_template_id": "id-new-et", "template_name": "new_email"}
            ]
        })))
        .mount(&server)
        .await;
    Mock::given(method("GET"))
        .and(path("/templates/email/info"))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "template_name": "new_email",
            "subject": "Hello",
            "body": "<a href=\"https://example.com\">{{ x | lid: 'xyz789' }}click</a>",
            "plaintext_body": "click here",
            "preheader": "News",
            "tags": [],
            "message": "success"
        })))
        .mount(&server)
        .await;

    let tmp = tempfile::tempdir().unwrap();
    let config_path = write_config(tmp.path(), &server.uri());
    // No local email template directory — brand-new resource.

    let tmp_path = tmp.path().to_path_buf();
    tokio::task::spawn_blocking(move || {
        Command::cargo_bin("braze-sync")
            .unwrap()
            .env("BRAZE_API_KEY", "test-key")
            .args(["--config", config_path.to_str().unwrap()])
            .args(["export", "--resource", "email_template"])
            .assert()
            .success();
    })
    .await
    .unwrap();

    let et_dir = tmp_path.join("email_templates/new_email");
    let html = fs::read_to_string(et_dir.join("body.html")).unwrap();
    assert!(
        html.contains("__BRAZESYNC__"),
        "new email template must be templatized, got:\n{html}"
    );
    assert!(
        !html.contains("xyz789"),
        "raw lid value must not persist for new email templates, got:\n{html}"
    );
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn export_existing_content_block_without_placeholders_skips_templatize() {
    // When a local file exists but deliberately has no placeholders,
    // templatization must be skipped (opt-out).
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path("/content_blocks/list"))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "content_blocks": [{"content_block_id": "id-noplc", "name": "no_placeholder"}]
        })))
        .mount(&server)
        .await;
    Mock::given(method("GET"))
        .and(path("/content_blocks/info"))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "name": "no_placeholder",
            "content": "<a href=\"https://example.com\">{{ x | lid: 'raw123' }}click</a>",
            "tags": []
        })))
        .mount(&server)
        .await;

    let tmp = tempfile::tempdir().unwrap();
    let config_path = write_config(tmp.path(), &server.uri());
    common::write_local_content_block(
        tmp.path(),
        "no_placeholder",
        "<a href=\"https://example.com\">{{ x | lid: 'old_raw' }}click</a>",
    );

    let tmp_path = tmp.path().to_path_buf();
    tokio::task::spawn_blocking(move || {
        Command::cargo_bin("braze-sync")
            .unwrap()
            .env("BRAZE_API_KEY", "test-key")
            .args(["--config", config_path.to_str().unwrap()])
            .args(["export", "--resource", "content_block"])
            .assert()
            .success();
    })
    .await
    .unwrap();

    let saved = fs::read_to_string(
        tmp_path
            .join("content_blocks")
            .join("no_placeholder.liquid"),
    )
    .unwrap();
    assert!(
        saved.contains("raw123"),
        "existing file without placeholders must keep raw values, got:\n{saved}"
    );
    assert!(
        !saved.contains("__BRAZESYNC__"),
        "must not introduce placeholders when local file opts out, got:\n{saved}"
    );
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn export_existing_email_template_without_placeholders_skips_templatize() {
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path("/templates/email/list"))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "templates": [
                {"email_template_id": "id-noplc-et", "template_name": "no_placeholder_et"}
            ]
        })))
        .mount(&server)
        .await;
    Mock::given(method("GET"))
        .and(path("/templates/email/info"))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "template_name": "no_placeholder_et",
            "subject": "Hello {{ x | lid: 'raw_subj' }}",
            "body": "<a href=\"https://example.com\">{{ x | lid: 'raw_html' }}click</a>",
            "plaintext_body": "{{ x | lid: 'raw_plain' }}",
            "preheader": "{{ x | lid: 'raw_pre' }}",
            "tags": [],
            "message": "success"
        })))
        .mount(&server)
        .await;

    let tmp = tempfile::tempdir().unwrap();
    let config_path = write_config(tmp.path(), &server.uri());
    common::write_local_email_template(
        tmp.path(),
        "no_placeholder_et",
        "Hello",
        "<a href=\"https://example.com\">{{ x | lid: 'old_html' }}click</a>",
        "{{ x | lid: 'old_plain' }}",
    );

    let tmp_path = tmp.path().to_path_buf();
    tokio::task::spawn_blocking(move || {
        Command::cargo_bin("braze-sync")
            .unwrap()
            .env("BRAZE_API_KEY", "test-key")
            .args(["--config", config_path.to_str().unwrap()])
            .args(["export", "--resource", "email_template"])
            .assert()
            .success();
    })
    .await
    .unwrap();

    let et_dir = tmp_path.join("email_templates/no_placeholder_et");
    let html = fs::read_to_string(et_dir.join("body.html")).unwrap();
    assert!(
        html.contains("raw_html"),
        "existing email template without placeholders must keep raw values, got:\n{html}"
    );
    assert!(
        !html.contains("__BRAZESYNC__"),
        "must not introduce placeholders when local email template opts out, got:\n{html}"
    );
}

// =====================================================================
// Custom Attribute — export against an *existing* registry
//
// The tests above start from no `registry.yaml`, so none of them can
// observe what a write does to entries already in the file. That was the
// gap behind #117: `export` replaced the file wholesale, silently
// deleting every entry the queried workspace did not return. These tests
// pin the membership rules instead of the file contents alone.
//
// Shared shape: Braze returns `remote_only` and `shared` (the latter
// with a type that disagrees with the registry); the registry also holds
// `registry_only`, which no workspace in this test has.
// =====================================================================

/// Two attributes, one of them (`shared`) typed `string` remotely while
/// the local registry declares `number` — the exact state `diff` reports
/// as `ℹ type mismatch … (run export to update)`.
async fn mock_ca_server() -> MockServer {
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path("/custom_attributes"))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "attributes": [
                { "name": "shared", "data_type": "string", "status": "Active" },
                { "name": "remote_only", "data_type": "number", "status": "Active" }
            ],
            "message": "success"
        })))
        .mount(&server)
        .await;
    server
}

const EXISTING_REGISTRY: &str = "\
attributes:
  - name: registry_only
    type: boolean
    description: no /users/track traffic in this workspace yet
  - name: shared
    type: number
";

fn run_export(config_path: std::path::PathBuf, extra: &[&str]) -> String {
    let mut cmd = Command::cargo_bin("braze-sync").unwrap();
    // Pin the log level: the binary defaults to `warn` on stderr, but
    // `EnvFilter::try_from_default_env` would honour a RUST_LOG inherited
    // from the developer's shell and silence the warnings asserted below.
    cmd.env("BRAZE_API_KEY", "test-key")
        .env("RUST_LOG", "warn")
        .args(["--config", config_path.to_str().unwrap()])
        .args(["export", "--resource", "custom_attribute"]);
    for a in extra {
        cmd.arg(a);
    }
    let out = cmd.assert().success().get_output().clone();
    String::from_utf8_lossy(&out.stderr).into_owned()
}

/// #117: an entry present in the registry but absent from the queried
/// workspace must survive. Braze creates attributes implicitly on first
/// `/users/track` traffic, so absence is not evidence the entry is wrong.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn export_ca_keeps_registry_only_entry() {
    let server = mock_ca_server().await;
    let tmp = tempfile::tempdir().unwrap();
    let config_path = common::write_config(tmp.path(), &server.uri());
    common::write_local_custom_attribute_registry(tmp.path(), EXISTING_REGISTRY);
    let registry_path = tmp.path().join("custom_attributes/registry.yaml");

    let stderr = tokio::task::spawn_blocking(move || run_export(config_path, &[]))
        .await
        .unwrap();

    let content = fs::read_to_string(&registry_path).unwrap();
    assert!(
        content.contains("registry_only"),
        "registry-only entry was dropped:\n{content}"
    );
    assert!(content.contains("remote_only"), "content:\n{content}");
    assert!(content.contains("shared"), "content:\n{content}");
    // The description on a kept entry is local-only state; nothing
    // refreshed it, so it must come through verbatim.
    assert!(
        content.contains("no /users/track traffic in this workspace yet"),
        "content:\n{content}"
    );
    // The count must not hide the kept entries behind "exported N".
    assert!(
        stderr.contains("refreshed 2") && stderr.contains("kept 1"),
        "stderr:\n{stderr}"
    );
}

/// The promise `diff`'s `type mismatch … (run export to update)` hint
/// makes. Merging must not turn export into a no-op for entries Braze
/// *did* return: those are still overwritten wholesale.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn export_ca_still_corrects_a_stale_type() {
    let server = mock_ca_server().await;
    let tmp = tempfile::tempdir().unwrap();
    let config_path = common::write_config(tmp.path(), &server.uri());
    common::write_local_custom_attribute_registry(tmp.path(), EXISTING_REGISTRY);
    let registry_path = tmp.path().join("custom_attributes/registry.yaml");

    tokio::task::spawn_blocking(move || run_export(config_path, &[]))
        .await
        .unwrap();

    let content = fs::read_to_string(&registry_path).unwrap();
    // Assert structurally, not by string position: `shared` is the last
    // entry only by alphabetical luck, so a `split(…).nth(1)` slice would
    // start spanning the next entry's fields the moment the mock gained
    // an attribute sorting after it — and would then pass on a file where
    // `shared` kept its stale type.
    assert_eq!(
        entry_field(&content, "shared", "type").as_deref(),
        Some("string"),
        "local `number` should have been corrected to Braze's `string`:\n{content}"
    );
    // Pin the neighbours too. `entry_field` is only worth more than a
    // positional slice if it actually isolates one entry, and these two
    // would come out wrong if it bled across entry boundaries —
    // `remote_only` is legitimately `number` here, which is why a
    // file-wide `!contains("type: number")` is the wrong assertion and
    // not a stronger one.
    assert_eq!(
        entry_field(&content, "remote_only", "type").as_deref(),
        Some("number"),
        "content:\n{content}"
    );
    assert_eq!(
        entry_field(&content, "registry_only", "type").as_deref(),
        Some("boolean"),
        "a kept entry's own type must not be touched:\n{content}"
    );
}

/// One field of one entry in a written `registry.yaml`, located by
/// walking entries rather than by substring position.
///
/// Deliberately not a YAML parse: `serde_norway` is a dependency of the
/// crate, not a dev-dependency, so it is not linkable from an
/// integration test. The written format is `save_registry`'s own output,
/// so the shape is fixed — `- name: x` opening an entry, fields at two
/// spaces — and relying on that is what makes the 2-vs-4-space fact
/// above visible in the test rather than buried.
fn entry_field(yaml: &str, name: &str, field: &str) -> Option<String> {
    let mut in_entry = false;
    for line in yaml.lines() {
        if let Some(rest) = line.strip_prefix("- name: ") {
            in_entry = rest.trim() == name;
            continue;
        }
        if in_entry {
            if let Some(rest) = line.strip_prefix(&format!("  {field}: ")) {
                return Some(rest.trim().to_string());
            }
        }
    }
    None
}

/// `exclude_patterns` means "managed out of band" — the docs say such
/// names are skipped by export. Before #117 they were skipped only in
/// the sense that they were filtered out of the remote list *and then
/// deleted from the file*.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn export_ca_keeps_excluded_entry_already_in_registry() {
    let server = mock_ca_server().await;
    let tmp = tempfile::tempdir().unwrap();
    let config_path =
        common::write_config_with_ca_excludes(tmp.path(), &server.uri(), &["^remote_only$"]);
    common::write_local_custom_attribute_registry(
        tmp.path(),
        "attributes:\n  - name: remote_only\n    type: number\n    description: managed out of band\n",
    );
    let registry_path = tmp.path().join("custom_attributes/registry.yaml");

    tokio::task::spawn_blocking(move || run_export(config_path, &[]))
        .await
        .unwrap();

    let content = fs::read_to_string(&registry_path).unwrap();
    assert!(
        content.contains("remote_only"),
        "excluded entry was dropped from the registry:\n{content}"
    );
    // Excluded means out of band in both directions: it is kept, not
    // refreshed, so the local annotation stays.
    assert!(
        content.contains("managed out of band"),
        "excluded entry was refreshed from Braze:\n{content}"
    );
    // Without this, a merge that assembled the file from local buckets
    // alone — never writing the remote list — would pass: the fixture
    // already contains everything the assertions above look for.
    assert!(
        content.contains("shared"),
        "the remote list was never written:\n{content}"
    );
}

/// `--prune` restores the pre-#117 rebuild for operators who do mean
/// "the remote is the truth".
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn export_ca_prune_drops_registry_only_entry() {
    let server = mock_ca_server().await;
    let tmp = tempfile::tempdir().unwrap();
    let config_path = common::write_config(tmp.path(), &server.uri());
    common::write_local_custom_attribute_registry(tmp.path(), EXISTING_REGISTRY);
    let registry_path = tmp.path().join("custom_attributes/registry.yaml");

    let stderr = tokio::task::spawn_blocking(move || run_export(config_path, &["--prune"]))
        .await
        .unwrap();

    let content = fs::read_to_string(&registry_path).unwrap();
    assert!(
        !content.contains("registry_only"),
        "--prune should have dropped it:\n{content}"
    );
    assert!(content.contains("remote_only"), "content:\n{content}");
    // Silence is what made this a data-loss bug; the count is the fix.
    assert!(
        stderr.contains("removed 1"),
        "prune must say what it removed:\n{stderr}"
    );
}

/// Merging needs to read the file, so a registry that no longer parses
/// fails the command instead of being silently overwritten. The previous
/// behaviour swallowed a one-character YAML slip and took 82 entries
/// with it.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn export_ca_fails_loudly_on_unparseable_registry() {
    let server = mock_ca_server().await;
    let tmp = tempfile::tempdir().unwrap();
    let config_path = common::write_config(tmp.path(), &server.uri());
    common::write_local_custom_attribute_registry(tmp.path(), "attributes:\n  - name: [oops\n");
    let registry_path = tmp.path().join("custom_attributes/registry.yaml");
    let before = fs::read_to_string(&registry_path).unwrap();

    let stderr = tokio::task::spawn_blocking(move || {
        let out = Command::cargo_bin("braze-sync")
            .unwrap()
            .env("BRAZE_API_KEY", "test-key")
            .args(["--config", config_path.to_str().unwrap()])
            .args(["export", "--resource", "custom_attribute"])
            .assert()
            .failure()
            .get_output()
            .clone();
        String::from_utf8_lossy(&out.stderr).into_owned()
    })
    .await
    .unwrap();

    // A bare `.failure()` also accepts a credential error, or a panic
    // raised before the registry is ever read — it would pass with the
    // fail-loud guarantee gone.
    assert!(
        stderr.contains("registry.yaml"),
        "the failure must name the file it could not parse:\n{stderr}"
    );

    assert_eq!(
        fs::read_to_string(&registry_path).unwrap(),
        before,
        "a failed export must leave the file alone"
    );
}

/// …and `--prune` stays usable on that file, because it is the way out.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn export_ca_prune_recovers_an_unparseable_registry() {
    let server = mock_ca_server().await;
    let tmp = tempfile::tempdir().unwrap();
    let config_path = common::write_config(tmp.path(), &server.uri());
    common::write_local_custom_attribute_registry(tmp.path(), "attributes:\n  - name: [oops\n");
    let registry_path = tmp.path().join("custom_attributes/registry.yaml");

    tokio::task::spawn_blocking(move || run_export(config_path, &["--prune"]))
        .await
        .unwrap();

    let content = fs::read_to_string(&registry_path).unwrap();
    assert!(content.contains("remote_only"), "content:\n{content}");
    assert!(content.contains("shared"), "content:\n{content}");
}

/// `diff` collapses duplicate registry names last-wins. `export` has to
/// agree, or the two commands cannot converge: whichever entry export
/// kept, diff would keep reporting the other as drift.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn export_ca_collapses_duplicate_registry_names_last_wins() {
    let server = mock_ca_server().await;
    let tmp = tempfile::tempdir().unwrap();
    let config_path = common::write_config(tmp.path(), &server.uri());
    common::write_local_custom_attribute_registry(
        tmp.path(),
        "attributes:\n\
         \x20 - name: registry_only\n    type: string\n    description: first\n\
         \x20 - name: registry_only\n    type: boolean\n    description: last\n",
    );
    let registry_path = tmp.path().join("custom_attributes/registry.yaml");

    let stderr = tokio::task::spawn_blocking(move || run_export(config_path, &[]))
        .await
        .unwrap();

    let content = fs::read_to_string(&registry_path).unwrap();
    assert_eq!(
        content.matches("- name: registry_only").count(),
        1,
        "duplicate should collapse to one entry:\n{content}"
    );
    assert!(content.contains("description: last"), "content:\n{content}");
    assert!(
        !content.contains("description: first"),
        "content:\n{content}"
    );
    assert!(stderr.contains("kept 1"), "stderr:\n{stderr}");
    // `diff` warns on this same input. Collapsing is the intended rule,
    // but doing it silently would leave the command that performs the
    // deletion as the quiet one of the two.
    assert!(
        stderr.contains("duplicate custom attribute name"),
        "export must warn about the collapsed duplicate:\n{stderr}"
    );
}

/// The rule that makes `--prune` safe to hand an operator: excluded
/// means the remote is not consulted about that name, so the remote's
/// silence is not evidence about it either. Without this test, moving
/// the `excluded` extend inside the `if !prune` block passes every
/// other test while `--prune` deletes out-of-band state and reports
/// that the workspace did not have it.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn export_ca_prune_keeps_excluded_entry() {
    let server = mock_ca_server().await;
    let tmp = tempfile::tempdir().unwrap();
    // `shared` is returned by Braze *and* excluded — the quadrant that
    // made the pre-review implementation misclassify it as registry-only.
    let config_path =
        common::write_config_with_ca_excludes(tmp.path(), &server.uri(), &["^shared$"]);
    common::write_local_custom_attribute_registry(
        tmp.path(),
        "attributes:\n  - name: shared\n    type: number\n    description: out of band\n",
    );
    let registry_path = tmp.path().join("custom_attributes/registry.yaml");

    let stderr = tokio::task::spawn_blocking(move || run_export(config_path, &["--prune"]))
        .await
        .unwrap();

    let content = fs::read_to_string(&registry_path).unwrap();
    assert!(
        content.contains("shared"),
        "--prune deleted an excluded entry:\n{content}"
    );
    assert!(
        content.contains("out of band"),
        "excluded entry was refreshed despite being excluded:\n{content}"
    );
    assert!(
        stderr.contains("kept 1 excluded entr"),
        "the excluded entry must be reported as excluded, not as removed \
         or as registry-only:\n{stderr}"
    );
    assert!(
        !stderr.contains("removed"),
        "nothing was removable here:\n{stderr}"
    );
}

/// `--prune` on a registry it could not read replaced an unknown number
/// of entries. Reporting `0` there would be the same silent destructive
/// write this change set out to stop, so the count says `unknown`.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn export_ca_prune_reports_unknown_removal_count_on_unparseable_registry() {
    let server = mock_ca_server().await;
    let tmp = tempfile::tempdir().unwrap();
    let config_path = common::write_config(tmp.path(), &server.uri());
    common::write_local_custom_attribute_registry(tmp.path(), "attributes:\n  - name: [oops\n");

    let stderr = tokio::task::spawn_blocking(move || run_export(config_path, &["--prune"]))
        .await
        .unwrap();

    assert!(
        stderr.contains("entries removed: unknown"),
        "a replacement of unknown size must say so:\n{stderr}"
    );
    assert!(
        !stderr.contains("removed 0"),
        "must not report zero removals for a file it could not read:\n{stderr}"
    );
}

/// The `done: N resource(s) written` trailer is the only observable of
/// `RegistryExport::written()`. Returning `refreshed` alone, or adding
/// the pruned entries, both compile and leave every other test green.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn export_ca_written_count_covers_kept_entries() {
    let server = mock_ca_server().await;
    let tmp = tempfile::tempdir().unwrap();
    let config_path = common::write_config(tmp.path(), &server.uri());
    common::write_local_custom_attribute_registry(tmp.path(), EXISTING_REGISTRY);

    let stderr = tokio::task::spawn_blocking(move || run_export(config_path, &[]))
        .await
        .unwrap();

    // 2 refreshed (`shared`, `remote_only`) + 1 kept (`registry_only`).
    assert!(
        stderr.contains("done: 3 resource(s) written"),
        "the written count must include kept entries — they are in the \
         file:\n{stderr}"
    );
}

/// …and under `--prune` the dropped entry must not be counted as
/// written, since it is not in the file.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn export_ca_written_count_excludes_pruned_entries() {
    let server = mock_ca_server().await;
    let tmp = tempfile::tempdir().unwrap();
    let config_path = common::write_config(tmp.path(), &server.uri());
    common::write_local_custom_attribute_registry(tmp.path(), EXISTING_REGISTRY);

    let stderr = tokio::task::spawn_blocking(move || run_export(config_path, &["--prune"]))
        .await
        .unwrap();

    assert!(
        stderr.contains("done: 2 resource(s) written"),
        "a pruned entry is not in the file and must not be counted:\n{stderr}"
    );
}

/// Both directions of the inert-`--prune` warning. Inverting its
/// condition would print "has no effect" on the one kind it does affect,
/// and stay silent on the kinds where it genuinely does nothing.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn export_prune_warns_only_when_it_cannot_apply() {
    let server = mock_ca_server().await;
    Mock::given(method("GET"))
        .and(path("/content_blocks/list"))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "content_blocks": [],
            "message": "success"
        })))
        .mount(&server)
        .await;
    let tmp = tempfile::tempdir().unwrap();
    let config_path = common::write_config(tmp.path(), &server.uri());
    let for_cb = config_path.clone();

    let cb_stderr = tokio::task::spawn_blocking(move || {
        let out = Command::cargo_bin("braze-sync")
            .unwrap()
            .env("BRAZE_API_KEY", "test-key")
            .env("RUST_LOG", "warn")
            .args(["--config", for_cb.to_str().unwrap()])
            .args(["export", "--resource", "content_block", "--prune"])
            .assert()
            .success()
            .get_output()
            .clone();
        String::from_utf8_lossy(&out.stderr).into_owned()
    })
    .await
    .unwrap();
    assert!(
        cb_stderr.contains("--prune affects custom_attribute only"),
        "an inert --prune must say so:\n{cb_stderr}"
    );

    let ca_stderr = tokio::task::spawn_blocking(move || run_export(config_path, &["--prune"]))
        .await
        .unwrap();
    assert!(
        !ca_stderr.contains("no effect"),
        "--prune does apply here; the warning must not fire:\n{ca_stderr}"
    );
}

/// The plural arm of the count wording. Every other test happens to use
/// exactly one entry, so `plural_y` could return "y" unconditionally.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn export_ca_kept_count_pluralizes() {
    let server = mock_ca_server().await;
    let tmp = tempfile::tempdir().unwrap();
    let config_path = common::write_config(tmp.path(), &server.uri());
    common::write_local_custom_attribute_registry(
        tmp.path(),
        "attributes:\n\
         \x20 - name: registry_only_a\n    type: string\n\
         \x20 - name: registry_only_b\n    type: string\n",
    );

    let stderr = tokio::task::spawn_blocking(move || run_export(config_path, &[]))
        .await
        .unwrap();

    assert!(
        stderr.contains("kept 2 registry-only entries"),
        "stderr:\n{stderr}"
    );
}
